server:
  port: 8080

spring:
  application:
  servlet:
    name: easybid

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auction_db}
    username: ${DB_USERNAME:auction}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: create-drop
    propertie:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  main:
    web-application-type: servlet
